import type {CountryLabelLayout,Position,PolygonGeometry} from "@/lib/map/country-label-layout";
import type {CountryEntity} from "./world-state";
import type {CountryLabelGlyphArtifact,GlyphMultiPolygon,GlyphPolygon} from "@/lib/map/country-label-glyph-geometry";

type Feature<G,P>={type:"Feature";geometry:G;properties:P};
type FeatureCollection<F>={type:"FeatureCollection";features:F[]};
export type CountryArtifactPolicy={placementMode:"curved-line"|"small-country-point";minZoom:number;priority:number;overlapAtClose?:boolean};
export type CountryFeature=Feature<PolygonGeometry,{countryId:string;nameKo:string;mapColor:string;playable:boolean;unitType:CountryEntity["unitType"]}>;
export type CountryBorderFeature=Feature<PolygonGeometry,{countryId:string}>;
export type CurvedLabelFeature=Feature<CountryLabelLayout["baseline"],{countryId:string;mapLabelKo:string;nameEn:string;fontSizeWorldUnits:number;targetTextWidthWorld:number;letterSpacing:number;priority:number;minZoom:number;placementMode:"curved-line";angle:number;insideRatio:number;baselineInsideRatio:number;geometryHash:string}>;
export type PointLabelFeature=Feature<{type:"Point";coordinates:Position},{countryId:string;mapLabelKo:string;nameKo:string;nameEn:string;fontSizeWorldUnits:number;targetTextWidthWorld:number;letterSpacing:number;priority:number;minZoom:number;placementMode:"small-country-point";angle:number;insideRatio:number;baselineInsideRatio:number;geometryHash:string;overlapAtClose:boolean}>;
export type CapitalFeature=Feature<{type:"Point";coordinates:Position},{countryId:string;nameKo:string;nameEn:string;capitalType:"national";labelRank:number}>;
export type GlyphLabelFeature=Feature<GlyphPolygon|GlyphMultiPolygon,{countryId:string;labelInstanceId:string;glyphIndex:number;codePoint:number;role:"fill"|"outline";geometryHash:string;fontHash:string;layoutVersion:string}>;
export type CountryMapArtifacts={countryId:string;countryFeature:CountryFeature;borderFeature:CountryBorderFeature;curvedLabelFeature?:CurvedLabelFeature;pointLabelFeature?:PointLabelFeature;capitalFeature?:CapitalFeature;glyphLabelArtifact?:CountryLabelGlyphArtifact;layout:CountryLabelLayout};

export function buildCountryMapArtifacts(country:CountryEntity,layout:CountryLabelLayout,policy:CountryArtifactPolicy,glyphLabelArtifact?:CountryLabelGlyphArtifact):CountryMapArtifacts{
  if(layout.countryId!==country.id)throw new Error(`Layout country mismatch: ${layout.countryId} !== ${country.id}`);
  if(glyphLabelArtifact&&(glyphLabelArtifact.countryId!==country.id||glyphLabelArtifact.geometryHash!==layout.geometryHash||glyphLabelArtifact.text!==country.names.mapKo))throw new Error(`Glyph artifact mismatch for ${country.id}`);
  const common={countryId:country.id,mapLabelKo:country.names.mapKo,nameEn:country.names.english,fontSizeWorldUnits:layout.fontSizeWorldUnits,targetTextWidthWorld:layout.targetTextWidthWorld,letterSpacing:layout.letterSpacing,priority:policy.priority,minZoom:policy.minZoom,angle:layout.angle,insideRatio:layout.insideRatio,baselineInsideRatio:layout.baselineInsideRatio,geometryHash:layout.geometryHash};
  const countryFeature:CountryFeature={type:"Feature",properties:{countryId:country.id,nameKo:country.names.shortKo,mapColor:country.mapColor,playable:country.playable,unitType:country.unitType},geometry:country.geometry};
  const borderFeature:CountryBorderFeature={type:"Feature",properties:{countryId:country.id},geometry:country.geometry};
  const curvedLabelFeature=policy.placementMode==="curved-line"?{type:"Feature" as const,properties:{...common,placementMode:"curved-line" as const},geometry:layout.baseline}:undefined;
  const pointLabelFeature=policy.placementMode==="small-country-point"?{type:"Feature" as const,properties:{...common,nameKo:country.names.shortKo,placementMode:"small-country-point" as const,overlapAtClose:policy.overlapAtClose??false},geometry:{type:"Point" as const,coordinates:layout.anchor}}:undefined;
  const capitalFeature=country.capital?.coordinates?{type:"Feature" as const,properties:{countryId:country.id,nameKo:country.capital.nameKo,nameEn:country.capital.nameEn,capitalType:"national" as const,labelRank:country.presentation.labelRank},geometry:{type:"Point" as const,coordinates:country.capital.coordinates}}:undefined;
  return {countryId:country.id,countryFeature,borderFeature,curvedLabelFeature,pointLabelFeature,capitalFeature,glyphLabelArtifact,layout};
}
const compareText=(a:string,b:string)=>a<b?-1:a>b?1:0;
const glyphFeatures=(artifacts:readonly CountryMapArtifacts[],role:"fill"|"outline")=>artifacts.flatMap(item=>item.glyphLabelArtifact?.glyphs.flatMap(glyph=>{const geometry=role==="fill"?glyph.fillGeometry:glyph.outlineGeometry;return geometry?[{type:"Feature" as const,properties:{countryId:item.countryId,labelInstanceId:item.glyphLabelArtifact!.labelInstanceId,glyphIndex:glyph.glyphIndex,codePoint:glyph.codePoint,role,geometryHash:item.glyphLabelArtifact!.geometryHash,fontHash:item.glyphLabelArtifact!.fontHash,layoutVersion:item.glyphLabelArtifact!.layoutVersion},geometry}]:[]} )??[]).sort((a,b)=>compareText(a.properties.countryId,b.properties.countryId)||compareText(a.properties.labelInstanceId,b.properties.labelInstanceId)||a.properties.glyphIndex-b.properties.glyphIndex);
export type CountryMapArtifactCollections={countries:FeatureCollection<CountryFeature>;borders:FeatureCollection<CountryBorderFeature>;curvedLabels:FeatureCollection<CurvedLabelFeature>;pointLabels:FeatureCollection<PointLabelFeature>;capitals:FeatureCollection<CapitalFeature>;glyphLabelFills:FeatureCollection<GlyphLabelFeature>;glyphLabelOutlines:FeatureCollection<GlyphLabelFeature>};
export function buildCountryMapArtifactCollections(artifacts:readonly CountryMapArtifacts[]):CountryMapArtifactCollections{return {countries:{type:"FeatureCollection",features:artifacts.map(item=>item.countryFeature)},borders:{type:"FeatureCollection",features:artifacts.map(item=>item.borderFeature)},curvedLabels:{type:"FeatureCollection",features:artifacts.flatMap(item=>item.curvedLabelFeature?[item.curvedLabelFeature]:[])},pointLabels:{type:"FeatureCollection",features:artifacts.flatMap(item=>item.pointLabelFeature?[item.pointLabelFeature]:[])},capitals:{type:"FeatureCollection",features:artifacts.flatMap(item=>item.capitalFeature?[item.capitalFeature]:[])},glyphLabelFills:{type:"FeatureCollection",features:glyphFeatures(artifacts,"fill")},glyphLabelOutlines:{type:"FeatureCollection",features:glyphFeatures(artifacts,"outline")}}}
export type CountryMapArtifactPatch={upserts:CountryMapArtifacts[];removedCountryIds:string[]};
export function applyCountryMapArtifactPatch(current:readonly CountryMapArtifacts[],patch:CountryMapArtifactPatch){const next=new Map(current.map(item=>[item.countryId,item]));for(const id of patch.removedCountryIds)next.delete(id);for(const item of patch.upserts)next.set(item.countryId,item);return [...next.values()]}
export type GeoJSONSetDataSource={setData:(data:unknown)=>void};
export type CountryMapSources={countries:GeoJSONSetDataSource;borders:GeoJSONSetDataSource;curvedLabels:GeoJSONSetDataSource;pointLabels:GeoJSONSetDataSource;capitals:GeoJSONSetDataSource;glyphLabelFills:GeoJSONSetDataSource;glyphLabelOutlines:GeoJSONSetDataSource};
export function updateCountryMapSources(sources:CountryMapSources,collections:CountryMapArtifactCollections){sources.countries.setData(collections.countries);sources.borders.setData(collections.borders);sources.curvedLabels.setData(collections.curvedLabels);sources.pointLabels.setData(collections.pointLabels);sources.capitals.setData(collections.capitals);sources.glyphLabelFills.setData(collections.glyphLabelFills);sources.glyphLabelOutlines.setData(collections.glyphLabelOutlines)}
