import type {Country} from "@/types/country";
import {computeCountryGeometryHash,type CountryLabelLayoutInput,type PolygonGeometry} from "@/lib/map/country-label-layout";
export type CountryNames={shortKo:string;officialKo:string;mapKo:string;english:string;searchAliases:string[]};
export type CountryCapital={nameKo:string;nameEn:string;coordinates:[number,number]|null};
export type CountryEntity={id:string;iso3:string;names:CountryNames;geometry:PolygonGeometry;mapColor:string;playable:boolean;unitType:Country["unitType"];capital:CountryCapital|null;presentation:{flagCode:string;region:string;center:[number,number];defaultZoom:number;labelRank:number}};
export type WorldState={countries:Record<string,CountryEntity>;revision:number};
export type CountryReplacement={removeCountryIds:string[];upsertCountries:CountryEntity[]};
export type WorldStateRollback={before:WorldState;appliedRevision:number};
export type CountryGeometryFeature={type:"Feature";properties:{countryId:string};geometry:PolygonGeometry};
export type CapitalFeature={type:"Feature";properties:{countryId:string;nameKo?:string;nameEn?:string};geometry:{type:"Point";coordinates:[number,number]}};
const aliases=(country:Country)=>[country.id,country.iso3,country.nameKo,country.mapLabelKo,country.nameEn].filter((value,index,all)=>value&&all.indexOf(value)===index);
export function createWorldState(metadata:readonly Country[],geometryFeatures:readonly CountryGeometryFeature[],capitalFeatures:readonly CapitalFeature[]=[]):WorldState{const geometryById=new Map(geometryFeatures.map(feature=>[feature.properties.countryId,feature.geometry])),capitalById=new Map(capitalFeatures.map(feature=>[feature.properties.countryId,feature])),countries:Record<string,CountryEntity>={};for(const country of metadata){if(countries[country.id])throw new Error(`Duplicate country id: ${country.id}`);const geometry=geometryById.get(country.id);if(!geometry)throw new Error(`Missing geometry for country: ${country.id}`);const capital=capitalById.get(country.id),hasCapital=country.capitalKo!=="—"||country.capitalEn!=="—";countries[country.id]={id:country.id,iso3:country.iso3,names:{shortKo:country.nameKo,officialKo:country.nameKo,mapKo:country.mapLabelKo,english:country.nameEn,searchAliases:aliases(country)},geometry,mapColor:country.mapColor,playable:country.playable,unitType:country.unitType,capital:hasCapital?{nameKo:country.capitalKo,nameEn:country.capitalEn,coordinates:capital?.geometry.coordinates??null}:null,presentation:{flagCode:country.flagCode,region:country.region,center:country.center,defaultZoom:country.defaultZoom,labelRank:country.labelRank}}}const extraGeometry=geometryFeatures.map(feature=>feature.properties.countryId).filter(id=>!countries[id]);if(extraGeometry.length)throw new Error(`Geometry without country metadata: ${extraGeometry.join(",")}`);return {countries,revision:0}}
export function countryEntityToLabelInput(country:CountryEntity,previousLayout?:CountryLabelLayoutInput["previousLayout"]):CountryLabelLayoutInput{return {countryId:country.id,geometry:country.geometry,label:country.names.mapKo,previousLayout}}
export function replaceCountryNames(state:WorldState,countryId:string,names:CountryNames):WorldState{const country=state.countries[countryId];if(!country)throw new Error(`Unknown country: ${countryId}`);return {...state,revision:state.revision+1,countries:{...state.countries,[countryId]:{...country,names}}}}
export function replaceCountryGeometry(state:WorldState,countryId:string,geometry:PolygonGeometry):WorldState{const country=state.countries[countryId];if(!country)throw new Error(`Unknown country: ${countryId}`);return {...state,revision:state.revision+1,countries:{...state.countries,[countryId]:{...country,geometry}}}}
export function applyCountryReplacement(state:WorldState,replacement:CountryReplacement):{state:WorldState;rollback:WorldStateRollback}{const removeIds=new Set(replacement.removeCountryIds);if(removeIds.size!==replacement.removeCountryIds.length)throw new Error("Duplicate country removal id");for(const id of removeIds)if(!state.countries[id])throw new Error(`Unknown country removal: ${id}`);const upsertIds=new Set<string>();for(const country of replacement.upsertCountries){if(!country.id||upsertIds.has(country.id))throw new Error(`Duplicate or empty country upsert id: ${country.id}`);if(state.countries[country.id]&&!removeIds.has(country.id))throw new Error(`Country upsert would overwrite an unrelated country: ${country.id}`);upsertIds.add(country.id)}const countries={...state.countries};for(const id of removeIds)delete countries[id];for(const country of replacement.upsertCountries)countries[country.id]=country;const next={countries,revision:state.revision+1};return {state:next,rollback:{before:state,appliedRevision:next.revision}}}
export function rollbackCountryReplacement(current:WorldState,rollback:WorldStateRollback):WorldState{if(current.revision!==rollback.appliedRevision)throw new Error(`WorldState changed after replacement: ${current.revision} !== ${rollback.appliedRevision}`);return rollback.before}
export function countryEntityGeometryHash(country:CountryEntity){return computeCountryGeometryHash(country.geometry)}
export function countryEntityLabelCacheKey(country:CountryEntity){return `${countryEntityGeometryHash(country)}:${country.names.mapKo}`}
export function countryEntityToCountry(country:CountryEntity):Country{return {id:country.id,iso3:country.iso3,nameKo:country.names.shortKo,nameEn:country.names.english,mapLabelKo:country.names.mapKo,capitalKo:country.capital?.nameKo??"—",capitalEn:country.capital?.nameEn??"—",flagCode:country.presentation.flagCode,region:country.presentation.region,mapColor:country.mapColor,center:country.presentation.center,defaultZoom:country.presentation.defaultZoom,unitType:country.unitType,playable:country.playable,labelRank:country.presentation.labelRank}}
