import {beforeAll,describe,it,expect} from 'vitest';import fs from 'node:fs';
import {prepareProductionCatalogSeed} from '../world/production-catalog-seed.server';import {readCatalogRuntimePair,type CatalogRuntimePair} from '../simulation/catalog-runtime';
import {catalogContractForConsumer} from '../projection/catalog-map-consumer-projection';import {readCatalogConsumerMetadata} from '../map/catalog-consumer-contract';
import {createWorldStateV3} from '../world/world-state-v3';
import {createSimulationStateV2} from '../simulation/simulation-state-v2';import {planTerritorialControl,planTerritorialControlBatch} from './territorial-control-planner';
let pair:CatalogRuntimePair,ids:string[],catalog:ReturnType<typeof catalogContractForConsumer>;
beforeAll(()=>{const p=prepareProductionCatalogSeed(),m=readCatalogConsumerMetadata(JSON.parse(fs.readFileSync(`public${p.bootstrap.metadata.path}`,'utf8')),p.bootstrap.catalogRef);catalog=catalogContractForConsumer(m);pair=readCatalogRuntimePair(p.serializedPair,catalog);ids=pair.world.territoryOrder.filter(id=>pair.world.territoriesById[id].ownerCountryId==='CHN').slice(0,10);});
const event={eventId:'event.permission',date:'2020-01-01',title:'권한',publicNarrative:'검증된 점령 권한',actorCountryIds:['KOR','CHN'],relatedFactIds:[],relatedSituationIds:[],causes:[],outcomeCategory:'military',significance:'minor'};
const setup=()=>{const authority={id:'tca:occupation',actorCountryId:'KOR',targetCountryId:'CHN',allowedTerritoryIds:ids,allowedOperations:['occupy'],validFrom:'2020-01-01',validTo:null,sourceEventId:event.eventId};return createSimulationStateV2({...pair.simulation,eventLog:[event],territorialControlAuthoritiesById:{[authority.id]:authority},territorialControlAuthorityOrder:[authority.id]},pair.world);};
const command=()=>({commandId:'command.occupy',type:'territory.occupy',expectedRevision:pair.world.revision,payload:{actorCountryId:'KOR',targetCountryId:'CHN',authorityId:'tca:occupation',expectedSimulationRevision:pair.simulation.revision,territoryIds:ids}});
describe('14-11 actual catalog occupation planner',()=>{
  it('waives only missing authority for development directives and keeps strict scope and invariants',()=>{
    const c=command(),simulation=pair.simulation,previous=process.env.NODE_ENV;
    try {
      Reflect.set(process.env,'NODE_ENV','test');
      expect(()=>planTerritorialControl({world:pair.world,simulation,command:c})).toThrow('INVALID_AUTHORITY');
      expect(planTerritorialControl({world:pair.world,simulation,command:c,debugDirective:true}).changes).toHaveLength(ids.length);
      const invalid={...c,payload:{...c.payload,targetCountryId:'KOR'}};
      expect(()=>planTerritorialControl({world:pair.world,simulation,command:invalid,debugDirective:true})).toThrow('INVALID_OCCUPATION_RELATION');
      expect(()=>planTerritorialControl({world:pair.world,simulation,command:{...c,expectedRevision:99},debugDirective:true})).toThrow('STALE_REVISION');
      expect(()=>planTerritorialControl({world:pair.world,simulation,command:{...c,payload:{...c.payload,territoryIds:Array(513).fill(ids[0])}},debugDirective:true})).toThrow();
      expect(()=>planTerritorialControl({world:pair.world,simulation:setup(),command:{...c,payload:{...c.payload,actorCountryId:'USA'}},debugDirective:true})).toThrow('INVALID_AUTHORITY');
      Reflect.set(process.env,'NODE_ENV','production');
      expect(()=>planTerritorialControl({world:pair.world,simulation,command:c,debugDirective:true})).toThrow('INVALID_AUTHORITY');
    } finally {if(previous===undefined)Reflect.deleteProperty(process.env,'NODE_ENV');else Reflect.set(process.env,'NODE_ENV',previous);}
  });
  it('plans one deterministic aggregate for ten territories without mutating the seed',()=>{const s=setup(),a=planTerritorialControl({world:pair.world,simulation:s,command:command()}),b=planTerritorialControl({world:pair.world,simulation:s,command:command()});expect(a).toEqual(b);expect(a.changes).toHaveLength(10);for(const c of a.changes){expect(c.after.ownerCountryId).toBe('CHN');expect(c.after.controllerCountryId).toBe('KOR');expect(pair.world.territoriesById[c.after.id]).toBe(c.before);}const batch=planTerritorialControlBatch({world:pair.world,simulation:s,commands:[command()]});expect(batch.effects).toHaveLength(1);expect(batch.affectedTerritoryIds).toEqual(ids);});
  it.each(['stale-world','stale-simulation','unknown-authority','wrong-actor','wrong-target','duplicate','unsorted','over-cap','unknown-country','scope','expired','wrong-operation','extra-field'])('rejects %s before any mutation',kind=>{const s=setup(),c=command();let date:string|undefined;
    if(kind==='stale-world')c.expectedRevision++;if(kind==='stale-simulation')c.payload.expectedSimulationRevision++;if(kind==='unknown-authority')c.payload.authorityId='tca:missing';if(kind==='wrong-actor')c.payload.actorCountryId='USA';if(kind==='wrong-target')c.payload.targetCountryId='USA';if(kind==='duplicate')c.payload.territoryIds=[ids[0],ids[0]];if(kind==='unsorted')c.payload.territoryIds=[...ids].reverse();if(kind==='over-cap')c.payload.territoryIds=Array(513).fill(ids[0]);if(kind==='unknown-country')c.payload.actorCountryId='ZZZ';if(kind==='scope')c.payload.territoryIds=[pair.world.territoryOrder.find(id=>!ids.includes(id))!];if(kind==='extra-field')Object.assign(c.payload,{coordinates:[0,0]});
    const simulation=kind==='expired'?createSimulationStateV2({...s,territorialControlAuthoritiesById:{'tca:occupation':{...s.territorialControlAuthoritiesById['tca:occupation'],validTo:'2020-01-01'}}},pair.world):s;if(kind==='expired')date='2020-01-02';if(kind==='wrong-operation')c.type='territory.liberate';expect(()=>planTerritorialControl({world:pair.world,simulation,command:c,date})).toThrow();expect(pair.world.territoriesById[ids[0]].controllerCountryId).toBe('CHN');});
  it('rejects null-owner liberation and invalid controller relations even with authority',()=>{const world=createWorldStateV3({...pair.world,territoriesById:{...pair.world.territoriesById,[ids[0]]:{...pair.world.territoriesById[ids[0]],ownerCountryId:null,controllerCountryId:'CHN'}}},catalog);const s=setup(),simulation=createSimulationStateV2({...s,territorialControlAuthoritiesById:{'tca:occupation':{...s.territorialControlAuthoritiesById['tca:occupation'],allowedOperations:['liberate']}}},world);expect(()=>planTerritorialControl({world,simulation,command:{...command(),type:'territory.liberate',payload:{...command().payload,territoryIds:[ids[0]]}}})).toThrow(/NULL_OWNER_LIBERATION/);});
  it('enforces the unchanged batch cap and rejects duplicate command IDs',()=>{expect(()=>planTerritorialControlBatch({world:pair.world,simulation:setup(),commands:Array(65).fill(command())})).toThrow(/CAP/);const one={...command(),payload:{...command().payload,territoryIds:[ids[0]]}},two={...command(),payload:{...command().payload,territoryIds:[ids[1]]}};expect(()=>planTerritorialControlBatch({world:pair.world,simulation:setup(),commands:[one,two]})).toThrow(/DUPLICATE/);});
  it('liberates to the legal owner and applies explicit new-owner/preserve transfer policies',()=>{
    const s=setup(),occupied=planTerritorialControlBatch({world:pair.world,simulation:s,commands:[command()]});const world={...pair.world,territoriesById:occupied.territoriesById};
    const grant=(operation:string,target:string)=>createSimulationStateV2({...s,territorialControlAuthoritiesById:{'tca:occupation':{...s.territorialControlAuthoritiesById['tca:occupation'],actorCountryId:'CHN',targetCountryId:target,allowedOperations:[operation]}}},world);
    const c={...command(),type:'territory.liberate',payload:{...command().payload,actorCountryId:'CHN',targetCountryId:'KOR'}};
    const liberated=planTerritorialControl({world,simulation:grant('liberate','KOR'),command:c});for(const change of liberated.changes)expect(change.after.controllerCountryId).toBe('CHN');
    for(const controllerPolicy of ['new-owner','preserve']){const simulation=grant('transfer','KOR');const transfer=planTerritorialControl({world:pair.world,simulation,command:{...c,type:'territory.transferOwnership',payload:{...c.payload,newOwnerCountryId:'KOR',controllerPolicy}}});for(const change of transfer.changes){expect(change.after.ownerCountryId).toBe('KOR');expect(change.after.controllerCountryId).toBe(controllerPolicy==='new-owner'?'KOR':'CHN');}}
  });
  it('rejects a retired actor even if its historical event exists',()=>{
    const world=createWorldStateV3({...pair.world,countriesById:Object.fromEntries(Object.entries(pair.world.countriesById).filter(([id])=>id!=='USA')),countryOrder:pair.world.countryOrder.filter(id=>id!=='USA'),retiredCountryIds:new Set([...pair.world.retiredCountryIds,'USA']),territoriesById:Object.fromEntries(Object.entries(pair.world.territoriesById).map(([id,t])=>[id,{...t,ownerCountryId:t.ownerCountryId==='USA'?'CHN':t.ownerCountryId,controllerCountryId:t.controllerCountryId==='USA'?'CHN':t.controllerCountryId}]))},catalog);
    expect(()=>planTerritorialControl({world,simulation:setup(),command:{...command(),payload:{...command().payload,actorCountryId:'USA'}}})).toThrow(/INACTIVE/);
  });
});
