import fs from "node:fs";
import path from "node:path";
import {describe,expect,it} from "vitest";
import {computeCountryLabelLayout as computeLayout,measureLabelText,recomputeCountryLabels,screenFontSize,type CountryLabelLayoutInput,type PolygonGeometry} from "./country-label-layout";
import {createMapLibreCountryLabelMetrics,measureTextWithFont} from "./font-metrics";

const rectangle=(x=0,y=0,w=20,h=10):PolygonGeometry=>({type:"Polygon",coordinates:[[[x,y],[x+w,y],[x+w,y+h],[x,y+h],[x,y]]]});
const fixtureTexts=["테스트 국가","대한민국","한국","콩고 민주 공화국","콩고공화국","가","날짜변경선","도넛 영토","회랑","본토","국가"],fontBuffer=fs.readFileSync(path.join(process.cwd(),"public/fonts/Noto Sans KR/NotoSansCJKkr-Regular.otf")),glyphPbfFiles=["0-255.pbf","256-511.pbf"].map(file=>fs.readFileSync(path.join(process.cwd(),"public/fonts/Open Sans Regular",file))),fontMetrics=createMapLibreCountryLabelMetrics(fontBuffer.buffer.slice(fontBuffer.byteOffset,fontBuffer.byteOffset+fontBuffer.byteLength),glyphPbfFiles,fixtureTexts),computeCountryLabelLayout=(input:CountryLabelLayoutInput)=>computeLayout({...input,policy:{fontMetrics,...input.policy}}),layout=computeCountryLabelLayout;

describe("shape-aware country label layout",()=>{
  it("is pure and deterministic",()=>{const input={countryId:"TST",geometry:rectangle(),label:"테스트 국가"};expect(layout(input)).toEqual(layout(input))});
  it("keeps anchor and footprint metrics inside",()=>{const result=computeCountryLabelLayout({countryId:"TST",geometry:rectangle(),label:"대한민국"});expect(result.anchor[0]).toBeGreaterThan(0);expect(result.anchor[0]).toBeLessThan(20);expect(result.anchor[1]).toBeGreaterThan(0);expect(result.anchor[1]).toBeLessThan(10);expect(result.insideRatio).toBeGreaterThan(.75);expect(result.coverageRatio).toBeGreaterThan(.5);expect(result.coverageRatio).toBeLessThan(.9);expect(Math.abs(result.angle)).toBeLessThanOrEqual(90)});
  it("measures Korean, spaces, long and short names from the real font",()=>{expect(measureLabelText("대한민국",.06,fontMetrics)).toBeGreaterThan(measureLabelText("한국",.06,fontMetrics));expect(measureLabelText("콩고 민주 공화국",.06,fontMetrics)).toBeGreaterThan(measureLabelText("콩고공화국",.06,fontMetrics));expect(measureTextWithFont(fontMetrics,"가")).toBeCloseTo(.92,4);expect(()=>measureTextWithFont(fontMetrics,"🙂")).toThrow(/do not contain/)});
  it("uses world-space exponential zoom",()=>{expect(screenFontSize(10,2)).toBe(screenFontSize(10,1)*2);expect(screenFontSize(10,3)).toBe(screenFontSize(10,1)*4)});
  it("unwraps an antimeridian polygon",()=>{const geometry:PolygonGeometry={type:"Polygon",coordinates:[[[170,50],[-170,50],[-170,65],[170,65],[170,50]]]};const result=computeCountryLabelLayout({countryId:"DAT",geometry,label:"날짜변경선"});expect(result.availableWidthWorld).toBeLessThan(100);expect(result.anchor[0]).toBeGreaterThanOrEqual(-180);expect(result.anchor[0]).toBeLessThanOrEqual(180)});
  it("preserves holes during projection and simplification",()=>{const geometry:PolygonGeometry={type:"Polygon",coordinates:[[[0,0],[20,0],[20,20],[0,20],[0,0]],[[6,6],[14,6],[14,14],[6,14],[6,6]]]};const result=computeCountryLabelLayout({countryId:"HOL",geometry,label:"도넛 영토"});expect(result.anchor[0]<6||result.anchor[0]>14||result.anchor[1]<6||result.anchor[1]>14).toBe(true);expect(result.insideRatio).toBeGreaterThan(0)});
  it("keeps a narrow corridor represented instead of stride dropping it",()=>{const geometry:PolygonGeometry={type:"Polygon",coordinates:[[[0,0],[8,0],[8,3],[20,3],[20,4],[8,4],[8,7],[0,7],[0,0]]]};const result=computeCountryLabelLayout({countryId:"COR",geometry,label:"회랑"});expect(result.anchor[0]).toBeGreaterThanOrEqual(0);expect(result.anchor[0]).toBeLessThanOrEqual(20);expect(result.geometryHash).toMatch(/^[0-9a-f]+$/)});
  it("selects a primary multipolygon component",()=>{const main=rectangle(0,0,20,10),island=rectangle(100,0,2,2);if(main.type!=="Polygon"||island.type!=="Polygon")throw new Error("fixture");const geometry:PolygonGeometry={type:"MultiPolygon",coordinates:[main.coordinates,island.coordinates]};const result=computeCountryLabelLayout({countryId:"MUL",geometry,label:"본토"});expect(result.anchor[0]).toBeLessThan(30);expect(result.componentIds).toHaveLength(1)});
  it("recomputes only changed geometry across five border changes",()=>{const base=computeCountryLabelLayout({countryId:"A",geometry:rectangle(),label:"국가"});const scenarios=[rectangle(0,0,15,10),rectangle(0,0,25,10),{type:"MultiPolygon",coordinates:[rectangle(0,0,8,10).coordinates,rectangle(12,0,8,10).coordinates]} as PolygonGeometry,rectangle(0,0,40,10),rectangle(0,0,20,3)];for(const geometry of scenarios){const [next]=recomputeCountryLabels([{countryId:"A",geometry,label:"국가",policy:{fontMetrics}}],{A:base});expect(next.countryId).toBe("A");expect(next.insideRatio).toBeGreaterThan(.6);expect(next.geometryHash).not.toBe("")}});
});
