import polygonClipping,{type MultiPolygon} from "polygon-clipping";
import {measureTextWithFont,type SerializableFontMetrics} from "./font-metrics.ts";

export type Position=[number,number];
export type PolygonGeometry={type:"Polygon";coordinates:Position[][]}|{type:"MultiPolygon";coordinates:Position[][][]};
export type CountryLabelPolicy={minComponentAreaRatio?:number;maxRotation?:number;minimumCurvatureRatio?:number;preferredCurvatureDirection?:-1|1;baselineOffsetRatio?:number;fontMetrics?:SerializableFontMetrics};
export type ComponentEvaluation={componentId:string;area:number;areaRatio:number;internalWidth:number;compactness:number;nearestDistance:number;score:number;selected:boolean;reason:string};
export type LabelSearchDiagnostics={centerCandidateCount:number;angleCandidates:number[];coarseCandidateCount:number;refinedCandidateCount:number;winningClearance:number;centerFallbackApplied:boolean;centerSpanGain:number};
export type CountryLabelLayoutInput={countryId:string;geometry:PolygonGeometry;label:string;previousLayout?:CountryLabelLayout;policy?:CountryLabelPolicy};
export type CountryLabelLayout={countryId:string;anchor:Position;angle:number;baseline:{type:"LineString";coordinates:Position[]};footprint:{type:"Polygon";coordinates:Position[][]};availableWidthWorld:number;availableHeightWorld:number;targetTextWidthWorld:number;fontSizeWorldUnits:number;letterSpacing:number;coverageRatio:number;insideRatio:number;sampledInsideRatio:number;baselineInsideRatio:number;confidence:number;componentIds:string[];componentEvaluations:ComponentEvaluation[];searchDiagnostics:LabelSearchDiagnostics;geometryHash:string};
export type CurvedBaselineInput={countryId:string;geometry:PolygonGeometry;anchor:Position;angle:number;width:number;availableHeight:number;previousBaseline?:Position[];policy?:CountryLabelPolicy};

type ProjectedPolygon=Position[][];
const rad=Math.PI/180,round=(n:number)=>Math.round(n*1e6)/1e6,clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const normalizeAngle=(a:number)=>{while(a>90)a-=180;while(a<-90)a+=180;return a};
const unwrap=(lon:number,reference:number)=>{while(lon-reference>180)lon-=360;while(lon-reference<-180)lon+=360;return lon};
const ringArea=(ring:Position[])=>Math.abs(ring.reduce((s,p,i)=>{const q=ring[(i+1)%ring.length];return s+p[0]*q[1]-q[0]*p[1]},0)/2);
const ringCenter=(ring:Position[]):Position=>{let x=0,y=0,a=0;for(let i=0;i<ring.length-1;i++){const p=ring[i],q=ring[i+1],cross=p[0]*q[1]-q[0]*p[1];x+=(p[0]+q[0])*cross;y+=(p[1]+q[1])*cross;a+=cross}return Math.abs(a)<1e-9?ring[0]:[x/(3*a),y/(3*a)]};
const inRing=(p:Position,r:Position[])=>{let inside=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside};
const inPolygon=(p:Position,poly:ProjectedPolygon)=>inRing(p,poly[0])&&!poly.slice(1).some(h=>inRing(p,h));
const inTerritory=(p:Position,polys:ProjectedPolygon[])=>polys.some(poly=>inPolygon(p,poly));

export function measureLabelText(label:string,letterSpacing=.06,fontMetrics?:SerializableFontMetrics){if(!fontMetrics)throw new Error("Country label font metrics are required");return measureTextWithFont(fontMetrics,label,letterSpacing)}

export function computeCountryGeometryHash(geometry:PolygonGeometry){let h=2166136261;const visit=(v:unknown)=>{if(Array.isArray(v))for(const x of v)visit(x);else if(typeof v==="number"){const s=Math.round(v*1e5).toString();for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619)}};visit(geometry.coordinates);return (h>>>0).toString(16)}
function unwrapRing(ring:Position[],reference:number):Position[]{if(!ring.length)return [];const result:Position[]=[[unwrap(ring[0][0],reference),ring[0][1]]];for(let i=1;i<ring.length;i++)result.push([unwrap(ring[i][0],result[i-1][0]),ring[i][1]]);const mean=result.reduce((sum,p)=>sum+p[0],0)/result.length,shift=Math.round((reference-mean)/360)*360;return result.map(p=>[p[0]+shift,p[1]] as Position)}
function perpendicularDistance(point:Position,start:Position,end:Position){const dx=end[0]-start[0],dy=end[1]-start[1];if(dx===0&&dy===0)return Math.hypot(point[0]-start[0],point[1]-start[1]);return Math.abs(dy*point[0]-dx*point[1]+end[0]*start[1]-end[1]*start[0])/Math.hypot(dx,dy)}
function simplifyOpen(points:Position[],tolerance:number):Position[]{if(points.length<=2)return points;let max=0,index=0;for(let i=1;i<points.length-1;i++){const distance=perpendicularDistance(points[i],points[0],points.at(-1)!);if(distance>max){max=distance;index=i}}if(max<=tolerance)return [points[0],points.at(-1)!];const left=simplifyOpen(points.slice(0,index+1),tolerance),right=simplifyOpen(points.slice(index),tolerance);return [...left.slice(0,-1),...right]}
function simplifyClosedRing(ring:Position[],tolerance:number){if(ring.length<=5)return ring.map(p=>[...p] as Position);const open=ring.slice(0,-1),anchor=open.reduce((best,p,i)=>p[0]<open[best][0]||p[0]===open[best][0]&&p[1]<open[best][1]?i:best,0),rotated=[...open.slice(anchor),...open.slice(0,anchor)],opposite=Math.floor(rotated.length/2),first=simplifyOpen(rotated.slice(0,opposite+1),tolerance),second=simplifyOpen([...rotated.slice(opposite),rotated[0]],tolerance),result=[...first.slice(0,-1),...second];if(result.length<4)return ring.map(p=>[...p] as Position);result[result.length-1]=[...result[0]];return result}
function projectGeometry(geometry:PolygonGeometry){const raw=geometry.type==="Polygon"?[geometry.coordinates]:geometry.coordinates,outerPoints=raw.flatMap(poly=>poly[0]),reference=outerPoints[0][0],unwrapped=raw.map(poly=>poly.map(ring=>unwrapRing(ring,reference))),all=unwrapped.flat(2) as Position[],lat0=all.reduce((s,p)=>s+p[1],0)/all.length,scale=Math.max(.15,Math.cos(lat0*rad)),project=(p:Position):Position=>[(p[0]-reference)*scale,p[1]-lat0],tolerance=.008,polygons=unwrapped.map(poly=>poly.map(ring=>simplifyClosedRing(ring.map(project),tolerance))),unproject=(p:Position):Position=>{let lon=p[0]/scale+reference;while(lon>180)lon-=360;while(lon<-180)lon+=360;return[lon,p[1]+lat0]};return {polygons,unproject,scale}}
function selectComponents(polygons:ProjectedPolygon[],policy:CountryLabelPolicy={}){
  const raw=polygons.map((poly,index)=>{const ring=poly[0],area=ringArea(ring),center=ringCenter(ring),xs=ring.map(p=>p[0]),ys=ring.map(p=>p[1]),width=Math.max(...xs)-Math.min(...xs),height=Math.max(...ys)-Math.min(...ys);return {poly,index,area,center,internalWidth:Math.min(width,height),compactness:area/Math.max(1e-9,width*height)}}),largestArea=Math.max(...raw.map(p=>p.area)),largestWidth=Math.max(...raw.map(p=>p.internalWidth)),ratio=policy.minComponentAreaRatio??.035;
  const parts=raw.map(part=>{const nearestDistance=Math.min(...raw.filter(other=>other!==part).map(other=>Math.hypot(part.center[0]-other.center[0],part.center[1]-other.center[1])),Infinity),areaRatio=part.area/largestArea,score=areaRatio*.65+part.internalWidth/Math.max(1e-9,largestWidth)*.25+part.compactness*.1;return {...part,nearestDistance,areaRatio,score}}).sort((a,b)=>b.score-a.score||a.index-b.index),seed=parts[0];
  const selected=new Set([seed.index]);
  const evaluations:ComponentEvaluation[]=parts.map(part=>{const isSelected=selected.has(part.index),reason=isSelected?"highest area-width-compactness score":part.areaRatio<ratio?"below minimum area ratio":"detached component excluded from label layout";return {componentId:`component-${part.index}`,area:round(part.area),areaRatio:round(part.areaRatio),internalWidth:round(part.internalWidth),compactness:round(part.compactness),nearestDistance:Number.isFinite(part.nearestDistance)?round(part.nearestDistance):-1,score:round(part.score),selected:isSelected,reason}}),chosen=parts.filter(part=>selected.has(part.index));return {polygons:chosen.map(x=>x.poly),ids:chosen.map(x=>`component-${x.index}`),fragmentation:chosen.length,evaluations}
}
function pcaAxis(polys:ProjectedPolygon[]){const points=polys.flatMap(p=>p[0]),c:Position=[points.reduce((s,p)=>s+p[0],0)/points.length,points.reduce((s,p)=>s+p[1],0)/points.length];let xx=0,xy=0,yy=0;for(const p of points){const x=p[0]-c[0],y=p[1]-c[1];xx+=x*x;xy+=x*y;yy+=y*y}const trace=xx+yy,separation=Math.hypot(xx-yy,2*xy);return {angle:normalizeAngle(.5*Math.atan2(2*xy,xx-yy)/rad),confidence:trace>0?separation/trace:0}}
function segmentDistance(point:Position,a:Position,b:Position){const dx=b[0]-a[0],dy=b[1]-a[1],t=clamp(((point[0]-a[0])*dx+(point[1]-a[1])*dy)/Math.max(1e-12,dx*dx+dy*dy),0,1);return Math.hypot(point[0]-(a[0]+t*dx),point[1]-(a[1]+t*dy))}
function boundaryClearance(point:Position,polys:ProjectedPolygon[]){let best=Infinity;for(const poly of polys)for(const ring of poly)for(let i=1;i<ring.length;i++)best=Math.min(best,segmentDistance(point,ring[i-1],ring[i]));return best}
function extent(center:Position,angle:number,polys:ProjectedPolygon[],sign:number){const a=angle*rad,d:Position=[Math.cos(a)*sign,Math.sin(a)*sign],bounds=polys.flatMap(p=>p[0]),span=Math.hypot(Math.max(...bounds.map(p=>p[0]))-Math.min(...bounds.map(p=>p[0])),Math.max(...bounds.map(p=>p[1]))-Math.min(...bounds.map(p=>p[1]))),step=Math.max(span/48,1e-4);let t=0;for(;t<span*1.5;t+=step)if(!inTerritory([center[0]+d[0]*t,center[1]+d[1]*t],polys))break;let lo=Math.max(0,t-step),hi=t;for(let i=0;i<6;i++){const mid=(lo+hi)/2;if(inTerritory([center[0]+d[0]*mid,center[1]+d[1]*mid],polys))lo=mid;else hi=mid}return lo}
function footprintRatio(center:Position,angle:number,width:number,height:number,polys:ProjectedPolygon[]){const a=angle*rad,c=Math.cos(a),s=Math.sin(a);let inside=0,total=0;for(let iy=-4;iy<=4;iy++)for(let ix=-8;ix<=8;ix++){const x=width*ix/16,y=height*iy/8,p:Position=[center[0]+x*c-y*s,center[1]+x*s+y*c];inside+=Number(inTerritory(p,polys));total++}return inside/total}
function footprintRing(center:Position,angle:number,width:number,height:number){const a=angle*rad,c=Math.cos(a),s=Math.sin(a),corners:Position[]=[[-width/2,-height/2],[width/2,-height/2],[width/2,height/2],[-width/2,height/2]];const ring=corners.map(([x,y])=>[center[0]+x*c-y*s,center[1]+x*s+y*c] as Position);ring.push([...ring[0]]);return ring}
function polygonArea(polygon:Position[][]){return Math.max(0,ringArea(polygon[0])-polygon.slice(1).reduce((sum,hole)=>sum+ringArea(hole),0))}
function denseFootprintRatio(center:Position,angle:number,width:number,height:number,polys:ProjectedPolygon[]){const a=angle*rad,c=Math.cos(a),s=Math.sin(a),columns=129,rows=65;let inside=0;for(let iy=0;iy<rows;iy++)for(let ix=0;ix<columns;ix++){const x=width*((ix+.5)/columns-.5),y=height*((iy+.5)/rows-.5);inside+=Number(inTerritory([center[0]+x*c-y*s,center[1]+x*s+y*c],polys))}return inside/(columns*rows)}
function exactFootprintRatio(center:Position,angle:number,width:number,height:number,polys:ProjectedPolygon[]){const footprint=footprintRing(center,angle,width,height);try{const intersectionArea=polys.reduce((total,polygon)=>{const intersection=polygonClipping.intersection([polygon] as MultiPolygon,[[footprint]]);return total+intersection.reduce((sum,part)=>sum+polygonArea(part as Position[][]),0)},0);return clamp(intersectionArea/Math.max(1e-12,width*height),0,1)}catch{return denseFootprintRatio(center,angle,width,height,polys)}}
function fitSmoothCountryCurve(points:Position[],center:Position,angle:number){const a=angle*rad,tangent:Position=[Math.cos(a),Math.sin(a)],normal:Position=[-Math.sin(a),Math.cos(a)],local=points.map(point=>{const dx=point[0]-center[0],dy=point[1]-center[1];return {x:dx*tangent[0]+dy*tangent[1],y:dx*normal[0]+dy*normal[1]}}),n=local.length,sx2=local.reduce((sum,p)=>sum+p.x*p.x,0),sx4=local.reduce((sum,p)=>sum+p.x**4,0),sy=local.reduce((sum,p)=>sum+p.y,0),sxy=local.reduce((sum,p)=>sum+p.x*p.y,0),sx2y=local.reduce((sum,p)=>sum+p.x*p.x*p.y,0),det=sx4*n-sx2*sx2,quadratic=Math.abs(det)>1e-9?(sx2y*n-sy*sx2)/det:0,intercept=Math.abs(det)>1e-9?(sx4*sy-sx2*sx2y)/det:sy/n,slope=sx2>1e-9?sxy/sx2:0;return local.map(({x})=>{const y=quadratic*x*x+slope*x+intercept;return [center[0]+tangent[0]*x+normal[0]*y,center[1]+tangent[1]*x+normal[1]*y] as Position})}
function territoryMidline(center:Position,angle:number,width:number,polys:ProjectedPolygon[],count=17){const a=angle*rad,tangent:Position=[Math.cos(a),Math.sin(a)],normal:Position=[-Math.sin(a),Math.cos(a)],all=polys.flatMap(poly=>poly[0]),span=Math.max(width,Math.hypot(Math.max(...all.map(p=>p[0]))-Math.min(...all.map(p=>p[0])),Math.max(...all.map(p=>p[1]))-Math.min(...all.map(p=>p[1])))),steps=96,points:Position[]=[];for(let i=0;i<count;i++){const t=i/(count-1)-.5,base:Position=[center[0]+tangent[0]*width*t,center[1]+tangent[1]*width*t],runs:Array<[number,number]>=[];let start:number|undefined;for(let j=0;j<=steps;j++){const offset=(j/steps-.5)*span,inside=inTerritory([base[0]+normal[0]*offset,base[1]+normal[1]*offset],polys);if(inside&&start===undefined)start=offset;if((!inside||j===steps)&&start!==undefined){runs.push([start,inside?offset:offset-span/steps]);start=undefined}}if(!runs.length)return undefined;const chosen=runs.sort((left,right)=>{const leftContains=left[0]<=0&&left[1]>=0,rightContains=right[0]<=0&&right[1]>=0;if(leftContains!==rightContains)return Number(rightContains)-Number(leftContains);const leftMid=(left[0]+left[1])/2,rightMid=(right[0]+right[1])/2;return Math.abs(leftMid)-Math.abs(rightMid)||(right[1]-right[0])-(left[1]-left[0])})[0],mid=(chosen[0]+chosen[1])/2;points.push([base[0]+normal[0]*mid,base[1]+normal[1]*mid])}for(let pass=0;pass<3;pass++)for(let i=1;i<points.length-1;i++)points[i]=[(points[i-1][0]+points[i][0]*2+points[i+1][0])/4,(points[i-1][1]+points[i][1]*2+points[i+1][1])/4];return fitSmoothCountryCurve(points,center,angle)}
function curvedLineInsideRatio(points:Position[],polys:ProjectedPolygon[]){let inside=0,total=0;for(let i=1;i<points.length;i++)for(let j=0;j<5;j++){const t=j/5,p:Position=[points[i-1][0]*(1-t)+points[i][0]*t,points[i-1][1]*(1-t)+points[i][1]*t];inside+=Number(inTerritory(p,polys));total++}inside+=Number(inTerritory(points.at(-1)!,polys));return inside/(total+1)}
function signedCurvature(points:Position[]){const a=points[0],b=points.at(-1)!,m=points[Math.floor(points.length/2)],dx=b[0]-a[0],dy=b[1]-a[1],length=Math.max(1e-9,Math.hypot(dx,dy));return (dx*(m[1]-a[1])-dy*(m[0]-a[0]))/length}
function baselineDifference(candidate:Position[],previous:Position[]){if(previous.length<2)return 0;const sample=(points:Position[],t:number)=>{const index=t*(points.length-1),lo=Math.floor(index),hi=Math.min(points.length-1,lo+1),f=index-lo;return [points[lo][0]*(1-f)+points[hi][0]*f,points[lo][1]*(1-f)+points[hi][1]*f] as Position};let rms=0;for(let i=0;i<17;i++){const a=sample(candidate,i/16),b=sample(previous,i/16);rms+=Math.hypot(a[0]-b[0],a[1]-b[1])**2}const direction=([p,q]:Position[])=>Math.atan2(q[1]-p[1],q[0]-p[0]),angleDelta=Math.abs(normalizeAngle((direction([candidate[0],candidate.at(-1)!])-direction([previous[0],previous.at(-1)!]))/rad));return Math.sqrt(rms/17)+angleDelta*.002+Math.abs(signedCurvature(candidate)-signedCurvature(previous))*.25}
export function computeCurvedCountryBaseline(input:CurvedBaselineInput):{type:"LineString";coordinates:Position[]}{
  const projected=projectGeometry(input.geometry),selection=selectComponents(projected.polygons,input.policy);
  // Re-project the anchor in the territory's coordinate frame.
  const anchorGeo=projected.unproject([0,0]),anchor:Position=[(unwrap(input.anchor[0],anchorGeo[0])-anchorGeo[0])*projected.scale,input.anchor[1]-anchorGeo[1]],previous=input.previousBaseline?.map(point=>[(unwrap(point[0],anchorGeo[0])-anchorGeo[0])*projected.scale,point[1]-anchorGeo[1]] as Position);
  const candidates=[1,.92,.84,.76,.68,.58,.48,.38,.28,.2].flatMap(widthScale=>{const width=input.width*widthScale,points=territoryMidline(anchor,input.angle,width,selection.polygons);if(!points)return [];const inside=curvedLineInsideRatio(points,selection.polygons),stability=previous?.length?baselineDifference(points,previous)/Math.max(width,1e-9):0,score=widthScale*2+inside*2-stability*.1;return [{points,inside,score,widthScale,stability}]}),eligible=candidates.filter(candidate=>candidate.inside>=.98).sort((a,b)=>b.score-a.score||b.widthScale-a.widthScale||a.stability-b.stability),chosen=eligible[0]??candidates.sort((a,b)=>b.inside-a.inside||b.score-a.score)[0];if(!chosen)throw new Error(`No polygon midline candidate for ${input.countryId}`);return {type:"LineString",coordinates:chosen.points.map(projected.unproject).map(point=>point.map(round) as Position)};
}

export function computeCountryLabelLayout(input:CountryLabelLayoutInput):CountryLabelLayout{
  const measureLabelText=(label:string,letterSpacing:number)=>{if(!input.policy?.fontMetrics)throw new Error(`Font metrics are required for ${input.countryId}`);return measureTextWithFont(input.policy.fontMetrics,label,letterSpacing)};
  const projected=projectGeometry(input.geometry),selection=selectComponents(projected.polygons,input.policy),polys=selection.polygons,points=polys.flatMap(p=>p[0]),box=[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))],axis=pcaAxis(polys),maxRotation=input.policy?.maxRotation??90;
  const angleSeed=axis.confidence<.18?0:axis.angle,angles=[angleSeed,angleSeed-15,angleSeed+15].map(normalizeAngle).filter((a,i,x)=>Math.abs(a)<=maxRotation&&x.findIndex(b=>Math.abs(b-a)<2)===i).sort((a,b)=>a-b);
  const clearanceCache=new Map<string,number>(),clearance=(p:Position)=>{const key=`${p[0].toFixed(6)},${p[1].toFixed(6)}`;if(!clearanceCache.has(key))clearanceCache.set(key,boundaryClearance(p,polys));return clearanceCache.get(key)!},centers:Position[]=[];for(const poly of polys){const c=ringCenter(poly[0]);if(inPolygon(c,poly))centers.push(c)}for(let y=1;y<6;y++)for(let x=1;x<8;x++){const p:Position=[box[0]+(box[2]-box[0])*x/8,box[1]+(box[3]-box[1])*y/6];if(inTerritory(p,polys))centers.push(p)}centers.sort((a,b)=>clearance(b)-clearance(a));
  const polygonCenter=ringCenter(polys[0][0]),originalCenter=inTerritory(polygonCenter,polys)?polygonCenter:centers[0],axisSpan=(center:Position)=>Math.max(...angles.map(angle=>extent(center,angle,polys,-1)+extent(center,angle,polys,1))),originalSpan=axisSpan(originalCenter),minimumFallbackClearance=clearance(centers[0])*.75,safeFallbackCenters=centers.filter(center=>clearance(center)>=minimumFallbackClearance),fallbackCenter=safeFallbackCenters.sort((a,b)=>axisSpan(b)-axisSpan(a)||clearance(b)-clearance(a))[0]??originalCenter,fallbackSpan=axisSpan(fallbackCenter),centerSpanGain=fallbackSpan/Math.max(1e-9,originalSpan),shapeDiagonal=Math.max(1e-9,Math.hypot(box[2]-box[0],box[3]-box[1])),centerFallbackApplied=axis.confidence>=.55&&originalSpan/shapeDiagonal<=.15&&centerSpanGain>=8,fixedCenter=centerFallbackApplied?fallbackCenter:originalCenter;
  const letterSpacing=.06,textUnits=measureLabelText(input.label,letterSpacing),widthUsage=clamp(.58+Math.log10(Math.max(1,ringArea(polys[0][0])))*.07,.55,.86),diagonal=Math.max(1,Math.hypot(box[2]-box[0],box[3]-box[1]));type Candidate={center:Position;angle:number;width:number;height:number;inside:number;score:number;stability:number;availableW:number;availableH:number;clearance:number};const evaluate=(center:Position,angle:number):Candidate=>{const availableW=extent(center,angle,polys,-1)+extent(center,angle,polys,1),availableH=extent(center,angle+90,polys,-1)+extent(center,angle+90,polys,1),width=availableW*widthUsage,height=Math.min(availableH*.72,width/Math.max(1,textUnits)),fittedWidth=Math.min(width,height*textUnits),inside=footprintRatio(center,angle,fittedWidth,height,polys),centrality=1-Math.hypot(center[0]-(box[0]+box[2])/2,center[1]-(box[1]+box[3])/2)/diagonal,clearanceValue=clearance(center),stability=input.previousLayout?1-Math.min(1,Math.hypot(center[0]-(input.previousLayout.anchor[0]-projected.unproject([0,0])[0])*projected.scale,center[1]-input.previousLayout.anchor[1])/diagonal):0,rotationPenalty=Math.max(0,Math.abs(angle)-55)/35*fittedWidth*.5,score=fittedWidth+availableH*.12+centrality*.35+Math.min(clearanceValue,availableH)*.18+inside*2-rotationPenalty-selection.fragmentation*.02;return {center,angle,width:fittedWidth,height,inside,score,stability,availableW,availableH,clearance:clearanceValue}},coarse=[fixedCenter].flatMap(center=>angles.map(angle=>evaluate(center,angle))).sort((a,b)=>b.score-a.score||b.stability-a.stability||a.angle-b.angle),top=coarse.slice(0,3),refined:Candidate[]=[];for(const candidate of top)for(const [dx,dy] of [[0,0]])for(const da of [-4,0,4]){const center:Position=[candidate.center[0]+dx,candidate.center[1]+dy],angle=normalizeAngle(candidate.angle+da);if(inTerritory(center,polys)&&Math.abs(angle)<=maxRotation)refined.push(evaluate(center,angle))}const ranked=[...coarse,...refined].sort((a,b)=>Math.abs(b.score-a.score)>.01?b.score-a.score:b.stability-a.stability||a.angle-b.angle),best=ranked[0];
  const insideTarget=.888,safer=ranked.find(candidate=>candidate.inside>=insideTarget&&candidate.width>=best.width*.55);if(safer)Object.assign(best,safer);
  const preciseScore=(item:{candidate:Candidate;exactInside:number})=>item.candidate.score+(item.exactInside-item.candidate.inside)*5;
  const preciseCandidates=[best,...ranked.filter(candidate=>candidate!==best).slice(0,15)].map(candidate=>({candidate,exactInside:exactFootprintRatio(candidate.center,candidate.angle,candidate.width,candidate.height,polys)})).sort((a,b)=>preciseScore(b)-preciseScore(a));
  const eligible=preciseCandidates.filter(item=>item.exactInside>=insideTarget&&item.candidate.width>=best.width*.55),qualityChoice=eligible[0]??preciseCandidates[0],qualityTolerance=Math.max(.25,Math.abs(preciseScore(qualityChoice))*.02),stablePool=eligible.filter(item=>preciseScore(item)>=preciseScore(qualityChoice)-qualityTolerance),preciseChoice=input.previousLayout&&stablePool.length>1?stablePool.sort((a,b)=>{const aa=projected.unproject(a.candidate.center),ba=projected.unproject(b.candidate.center),distanceA=Math.hypot(unwrap(aa[0],input.previousLayout!.anchor[0])-input.previousLayout!.anchor[0],aa[1]-input.previousLayout!.anchor[1])+Math.abs(normalizeAngle(a.candidate.angle-input.previousLayout!.angle))*.02,distanceB=Math.hypot(unwrap(ba[0],input.previousLayout!.anchor[0])-input.previousLayout!.anchor[0],ba[1]-input.previousLayout!.anchor[1])+Math.abs(normalizeAngle(b.candidate.angle-input.previousLayout!.angle))*.02;return distanceA-distanceB})[0]:qualityChoice;
  Object.assign(best,preciseChoice.candidate);const exactInside=preciseChoice.exactInside,projectedFootprint=footprintRing(best.center,best.angle,best.width,best.height),footprint:{type:"Polygon";coordinates:Position[][]}={type:"Polygon",coordinates:[projectedFootprint.map(projected.unproject)]};
  if(!best)throw new Error(`No label candidate for ${input.countryId}`);const anchor=projected.unproject(best.center),labelThickness=best.availableH,baselineWidth=Math.min(best.availableW*.96,best.width*1.35),baseline=computeCurvedCountryBaseline({countryId:input.countryId,geometry:input.geometry,anchor,angle:best.angle,width:baselineWidth,availableHeight:labelThickness,previousBaseline:input.previousLayout?.baseline.coordinates,policy:input.policy});const baselineInside=curvedLineInsideRatio(baseline.coordinates.map(p=>[(unwrap(p[0],projected.unproject([0,0])[0])-projected.unproject([0,0])[0])*projected.scale,p[1]-projected.unproject([0,0])[1]] as Position),polys);const worldScale=512/360,availableWidthWorld=best.availableW*worldScale,targetTextWidthWorld=best.width*worldScale,fontSizeWorldUnits=targetTextWidthWorld/textUnits;
  return {countryId:input.countryId,anchor:anchor.map(round) as Position,angle:round(normalizeAngle(best.angle)),baseline,footprint,availableWidthWorld:round(availableWidthWorld),availableHeightWorld:round(labelThickness*worldScale),targetTextWidthWorld:round(targetTextWidthWorld),fontSizeWorldUnits:round(fontSizeWorldUnits),letterSpacing,coverageRatio:round(best.width/best.availableW),insideRatio:round(exactInside),sampledInsideRatio:round(best.inside),baselineInsideRatio:round(baselineInside),confidence:round(clamp(exactInside*.65+Math.min(1,best.availableH/Math.max(.01,best.width))*.25+(1-selection.fragmentation*.03)*.1,0,1)),componentIds:selection.ids,componentEvaluations:selection.evaluations,searchDiagnostics:{centerCandidateCount:centers.length,angleCandidates:angles.map(round),coarseCandidateCount:coarse.length,refinedCandidateCount:refined.length,winningClearance:round(best.clearance),centerFallbackApplied,centerSpanGain:round(centerSpanGain)},geometryHash:computeCountryGeometryHash(input.geometry)}
}

export function recomputeCountryLabels(changedCountries:CountryLabelLayoutInput[],previousLayouts:Record<string,CountryLabelLayout>={}){return changedCountries.map(input=>computeCountryLabelLayout({...input,previousLayout:input.previousLayout??previousLayouts[input.countryId]}))}
export const screenFontSize=(fontSizeWorldUnits:number,zoom:number)=>fontSizeWorldUnits*2**zoom;
