import {describe,expect,it} from "vitest";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import metrics from "@/data/country-label-metrics-2020.json";
import countries from "@/data/countries-2020.json";
import type {CountryLabelLayout,PolygonGeometry} from "./country-label-layout";
import {buildCountryLabelGlyphArtifact,countryLabelTypographyPolicy,type CountryLabelGlyphGeometryInput,type GlyphMultiPolygon,type GlyphPolygon} from "./country-label-glyph-geometry";
import {shapeFontOutlines} from "./font-outline";

const geometry=JSON.parse(fs.readFileSync(path.join(process.cwd(),"public/data/maps/countries-10m.geojson"),"utf8")) as {features:Array<{properties:{countryId:string};geometry:PolygonGeometry}>},fontBytes=fs.readFileSync(path.join(process.cwd(),"public/fonts/Noto Sans KR/NotoSansCJKkr-Regular.otf")),fontHash=crypto.createHash("sha256").update(fontBytes).digest("hex"),metricById=new Map((metrics as unknown as CountryLabelLayout[]).map(metric=>[metric.countryId,metric])),countryById=new Map(countries.map(country=>[country.id,country])),geometryById=new Map(geometry.features.map(feature=>[feature.properties.countryId,feature.geometry]));
const rings=(geometry:GlyphPolygon|GlyphMultiPolygon)=>geometry.type==="Polygon"?geometry.coordinates:geometry.coordinates.flat();
const polygons=(geometry:GlyphPolygon|GlyphMultiPolygon)=>geometry.type==="Polygon"?[geometry.coordinates]:geometry.coordinates;
const closed=(ring:[number,number][])=>ring.length>=4&&ring[0][0]===ring.at(-1)![0]&&ring[0][1]===ring.at(-1)![1];
const selfIntersections=(ring:[number,number][])=>{const orient=(a:[number,number],b:[number,number],c:[number,number])=>Math.sign((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]));let count=0;for(let i=0;i<ring.length-1;i++)for(let j=i+1;j<ring.length-1;j++){if(Math.abs(i-j)<=1||(i===0&&j===ring.length-2))continue;const a=ring[i],b=ring[i+1],c=ring[j],d=ring[j+1];if(orient(a,b,c)*orient(a,b,d)<0&&orient(c,d,a)*orient(c,d,b)<0)count++}return count};
const artifact=(countryId:"AUS"|"RUS"|"CHL"|"IDN"|"CHN"|"USA",options:Partial<CountryLabelGlyphGeometryInput>={})=>{const text=countryById.get(countryId)!.mapLabelKo,font=shapeFontOutlines(fontBytes,fontHash,text,1,.06);return buildCountryLabelGlyphArtifact({countryId,text,geometry:geometryById.get(countryId)!,layout:metricById.get(countryId)!,font,...countryLabelTypographyPolicy(countryId,[...text].length),...options})};

describe("8-3 pure world-space glyph geometry",()=>{
  if(process.env.PAX_FIX08_3_SUMMARY==="1")for(const countryId of ["AUS","RUS"] as const){const value=artifact(countryId);console.log("FIX08_3_SUMMARY",JSON.stringify({countryId,text:value.text,glyphs:value.glyphs.length,hash:crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"),boundsWorld:value.boundsWorld,effectiveTerritoryWidthWorld:value.effectiveTerritoryWidthWorld,availableThicknessWorld:value.availableThicknessWorld,glyphScale:value.glyphScale,glyphHeightWorld:value.glyphHeightWorld,naturalGlyphSpan:value.naturalGlyphSpan,targetSpanRatio:value.targetSpanRatio,targetLabelSpan:value.targetLabelSpan,trackingWorld:value.trackingWorld,trackingEm:value.trackingEm,labelWidthWorld:value.labelWidthWorld,widthRatio:value.widthRatio,insideRatio:value.insideRatio,vertices:value.glyphs.flatMap(g=>rings(g.fillGeometry)).flat().length,holes:value.glyphs.flatMap(g=>polygons(g.fillGeometry)).reduce((sum,p)=>sum+Math.max(0,p.length-1),0)}))}
  if(process.env.PAX_FIX08_11_SUMMARY==="1")for(const countryId of ["RUS","AUS","CHL","IDN"] as const){const value=artifact(countryId),raw=artifact(countryId,{baselineSmoothingPasses:0}),angles=value.glyphs.map(glyph=>glyph.tangentAngle),adjacentDeltas=angles.slice(1).map((angle,index)=>Math.abs(angle-angles[index]));console.log("FIX08_11_SUMMARY",JSON.stringify({countryId,text:value.text,artifactHash:crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"),baselineSampleCount:value.baseline.coordinates.length,tangentAngles:angles,maxAbsoluteAngle:Math.max(...angles.map(Math.abs)),maxAdjacentDelta:adjacentDeltas.length?Math.max(...adjacentDeltas):0,insideRatioBeforeSmoothing:raw.insideRatio,insideRatioAfterSmoothing:value.insideRatio,baselineDistances:value.glyphs.map(glyph=>glyph.baselineDistanceWorld)}))}
  if(process.env.PAX_FIX08_12_SUMMARY==="1")for(const countryId of ["RUS","CHN","AUS","USA","CHL","IDN"] as const){const value=artifact(countryId),common=artifact(countryId,{glyphHeightRatio:.23}),angles=value.glyphs.map(glyph=>glyph.tangentAngle),deltas=angles.slice(1).map((angle,index)=>Math.abs(angle-angles[index]));console.log("FIX08_12_SUMMARY",JSON.stringify({countryId,text:value.text,glyphCount:value.glyphs.length,glyphHeightRatio:value.glyphHeightWorld/value.availableThicknessWorld,labelSpanRatio:value.targetSpanRatio,trackingEm:value.trackingEm,maxAbsoluteAngle:Math.max(...angles.map(Math.abs)),maxAdjacentAngleDelta:deltas.length?Math.max(...deltas):0,insideRatio:value.insideRatio,commonPolicy:{glyphHeightRatio:common.glyphHeightWorld/common.availableThicknessWorld,labelSpanRatio:common.targetSpanRatio,trackingEm:common.trackingEm,insideRatio:common.insideRatio},override:countryId==="CHL"?"glyphHeightRatio 0.72 for narrow vertical territory readability":null}))}
  it.each(["AUS","RUS"] as const)("builds deterministic valid %s glyph artifacts",countryId=>{const first=artifact(countryId),second=artifact(countryId);expect(first).toEqual(second);expect(crypto.createHash("sha256").update(JSON.stringify(first)).digest("hex")).toBe(crypto.createHash("sha256").update(JSON.stringify(second)).digest("hex"));expect(first.glyphs.map(glyph=>glyph.glyphIndex)).toEqual([...first.text].map((_,index)=>index));expect(first.glyphs.map(glyph=>glyph.codePoint)).toEqual([...first.text].map(character=>character.codePointAt(0)));expect(first.glyphs.every(glyph=>rings(glyph.fillGeometry).every(closed))).toBe(true);expect(first.glyphs.flatMap(glyph=>rings(glyph.fillGeometry)).reduce((sum,ring)=>sum+selfIntersections(ring),0)).toBe(0);expect(first.widthRatio).toBeCloseTo(first.labelWidthWorld/first.effectiveTerritoryWidthWorld,6);expect(first.glyphs.every((glyph,index,list)=>index===0||glyph.baselineDistanceWorld>list[index-1].baselineDistanceWorld)).toBe(true)});
  it("separates representative glyph height from tracked label span",()=>{const australia=artifact("AUS"),russia=artifact("RUS");for(const [countryId,value] of [["AUS",australia],["RUS",russia]] as const){expect(value.layoutVersion).toBe("world-glyph-v4-typography");expect(value.glyphScale).toBeGreaterThan(0);expect(value.glyphHeightWorld).toBeCloseTo(value.availableThicknessWorld*countryLabelTypographyPolicy(countryId,[...value.text].length).glyphHeightRatio!,4);expect(value.targetLabelSpan).toBeGreaterThanOrEqual(value.naturalGlyphSpan);expect(value.trackingWorld).toBeCloseTo((value.targetLabelSpan-value.naturalGlyphSpan)/(value.glyphs.length-1),4);expect(value.trackingEm).toBeCloseTo(value.trackingWorld/(value.glyphScale*1000),3)}expect(russia.glyphHeightWorld).toBeLessThanOrEqual(russia.availableThicknessWorld*.42);expect(australia.glyphHeightWorld).toBeGreaterThan(4)});
  it.each(["RUS","CHN","AUS","USA","CHL","IDN"] as const)("meets revised visual-containment typography policy for %s",countryId=>{const value=artifact(countryId),angles=value.glyphs.map(glyph=>glyph.tangentAngle);expect(value.glyphHeightWorld/value.availableThicknessWorld).toBeGreaterThanOrEqual(.1799);expect(value.glyphHeightWorld/value.availableThicknessWorld).toBeLessThanOrEqual(.72);expect(value.trackingEm).toBeGreaterThanOrEqual(0);expect(value.trackingEm).toBeLessThanOrEqual(3.5);expect(angles.every(angle=>Math.abs(angle)<=value.maxAbsoluteGlyphAngle)).toBe(true);expect(angles.slice(1).every((angle,index)=>Math.abs(angle-angles[index])<=value.maxAdjacentAngleDelta)).toBe(true);expect(value.insideRatio).toBeGreaterThan(.85)});
  it("enlarges short labels with the same adaptive policy and no country override",()=>{const chile=artifact("CHL"),china=artifact("CHN");expect(chile.glyphHeightWorld/chile.availableThicknessWorld).toBeGreaterThan(china.glyphHeightWorld/china.availableThicknessWorld);expect(chile.glyphHeightWorld/chile.availableThicknessWorld).toBeLessThanOrEqual(.5);expect(chile.trackingEm).toBeGreaterThanOrEqual(0);expect(chile.trackingEm).toBeLessThanOrEqual(.8);expect(chile.insideRatio).toBeGreaterThan(.85)});
  it.each(["RUS","AUS","CHL","IDN"] as const)("stabilizes %s tangent angles and keeps glyph progression monotonic",countryId=>{const value=artifact(countryId),angles=value.glyphs.map(glyph=>glyph.tangentAngle),distances=value.glyphs.map(glyph=>glyph.baselineDistanceWorld);expect(value.baseline.coordinates).toHaveLength(25);expect(angles.every(angle=>Math.abs(angle)<=value.maxAbsoluteGlyphAngle+1e-6)).toBe(true);expect(angles.slice(1).every((angle,index)=>Math.abs(angle-angles[index])<=value.maxAdjacentAngleDelta+1e-6)).toBe(true);expect(distances.slice(1).every((distance,index)=>distance>distances[index])).toBe(true);expect(value.glyphs.flatMap(glyph=>rings(glyph.fillGeometry)).reduce((sum,ring)=>sum+selfIntersections(ring),0)).toBe(0)});
  it.each(["CHL","IDN"] as const)("does not worsen %s corridor or containment after baseline smoothing",countryId=>{const raw=artifact(countryId,{baselineSmoothingPasses:0}),smoothed=artifact(countryId),movement=Math.max(...smoothed.baseline.coordinates.map((point,index)=>Math.hypot(point[0]-raw.baseline.coordinates[index][0],point[1]-raw.baseline.coordinates[index][1])*512/360));expect(movement).toBeLessThan(smoothed.availableThicknessWorld*.02);expect(smoothed.insideRatio).toBeGreaterThanOrEqual(raw.insideRatio-.01)});
  it("limits a noisy synthetic baseline without changing glyph order",()=>{const base=metricById.get("AUS")!,text="가나다라마바사",font=shapeFontOutlines(fontBytes,fontHash,text,1,.06),layout={...base,baseline:{type:"LineString" as const,coordinates:Array.from({length:17},(_,index)=>[120+index*.4,-25+(index%2?2:-2)] as [number,number])}},value=buildCountryLabelGlyphArtifact({countryId:"AUS",text,geometry:geometryById.get("AUS")!,layout,font,targetSpanRatio:.75,maxAbsoluteGlyphAngle:30,maxAdjacentAngleDelta:8});expect(value.glyphs.map(glyph=>glyph.glyphIndex)).toEqual([0,1,2,3,4,5,6]);expect(value.glyphs.every(glyph=>Math.abs(glyph.tangentAngle)<=30)).toBe(true);expect(value.glyphs.slice(1).every((glyph,index)=>Math.abs(glyph.tangentAngle-value.glyphs[index].tangentAngle)<=8.000001)).toBe(true)});
  it.each([["가",1],["가나",2],["가나다라",4],["가나다라마바사",7]] as const)("keeps deterministic scale/tracking for %s (%i glyphs)",(text,count)=>{const layout=metricById.get("AUS")!,font=shapeFontOutlines(fontBytes,fontHash,text,1,.06),build=()=>buildCountryLabelGlyphArtifact({countryId:"AUS",text,geometry:geometryById.get("AUS")!,layout,font}),first=build(),second=build();expect(first).toEqual(second);expect(first.glyphs).toHaveLength(count);expect(first.glyphScale).toBe(second.glyphScale);expect(first.naturalGlyphSpan).toBe(second.naturalGlyphSpan);expect(first.targetLabelSpan).toBe(second.targetLabelSpan);if(count===1)expect(first.trackingWorld).toBe(0);else expect(first.trackingWorld).toBeCloseTo((first.targetLabelSpan-first.naturalGlyphSpan)/(count-1),5);expect(crypto.createHash("sha256").update(JSON.stringify(first)).digest("hex")).toBe(crypto.createHash("sha256").update(JSON.stringify(second)).digest("hex"));expect(first.glyphs.map(glyph=>glyph.glyphIndex)).toEqual(Array.from({length:count},(_,index)=>index));expect(first.glyphs.flatMap(glyph=>rings(glyph.fillGeometry)).reduce((sum,ring)=>sum+selfIntersections(ring),0)).toBe(0)});
  it("preserves Korean holes as polygon interior rings",()=>{const australia=artifact("AUS"),russia=artifact("RUS"),holeCount=(value:ReturnType<typeof artifact>)=>value.glyphs.flatMap(glyph=>polygons(glyph.fillGeometry)).reduce((sum,polygon)=>sum+Math.max(0,polygon.length-1),0);expect(holeCount(australia)).toBeGreaterThanOrEqual(1);expect(holeCount(russia)).toBeGreaterThanOrEqual(1)});
  it("splits and wraps dateline glyphs without world-spanning rings",()=>{const text="호",font=shapeFontOutlines(fontBytes,fontHash,text,1),layout={...metricById.get("AUS")!,countryId:"DAT",baseline:{type:"LineString" as const,coordinates:[[179.2,0],[-179.2,0]] as [number,number][]},availableWidthWorld:3,targetTextWidthWorld:2.1,geometryHash:"dateline"},result=buildCountryLabelGlyphArtifact({countryId:"DAT",text,geometry:{type:"Polygon",coordinates:[[[179,-2],[-179,-2],[-179,2],[179,2],[179,-2]]]} as PolygonGeometry,layout,font});expect(result.glyphs[0].fillGeometry.type).toBe("MultiPolygon");for(const ring of rings(result.glyphs[0].fillGeometry))expect(Math.max(...ring.map(p=>p[0]))-Math.min(...ring.map(p=>p[0]))).toBeLessThan(180)});
  it("rejects empty text, missing glyphs, and zero-length baselines",()=>{expect(()=>shapeFontOutlines(fontBytes,fontHash,"",1)).toThrow("empty");expect(()=>shapeFontOutlines(fontBytes,fontHash,String.fromCodePoint(0x10ffff),1)).toThrow("Missing glyph");const text="호",font=shapeFontOutlines(fontBytes,fontHash,text,1),layout={...metricById.get("AUS")!,countryId:"ZERO",baseline:{type:"LineString" as const,coordinates:[[0,0],[0,0]] as [number,number][]}};expect(()=>buildCountryLabelGlyphArtifact({countryId:"ZERO",text,geometry:{type:"Polygon",coordinates:[]} as PolygonGeometry,layout,font})).toThrow("positive")});
});
