export type SerializableFontMetrics={family:string;unitsPerEm:number;advances:Record<string,number>};
export const MAPLIBRE_COUNTRY_LABEL_FONT={textFont:"Open Sans Regular",glyphSource:"/fonts/{fontstack}/{range}.pbf",localIdeographFontFamily:"Noto Sans KR Local",calculationFont:"MapLibre Open Sans Regular + local Noto Sans KR"} as const;

const tag=(view:DataView,offset:number)=>String.fromCharCode(view.getUint8(offset),view.getUint8(offset+1),view.getUint8(offset+2),view.getUint8(offset+3));
export function extractFontMetrics(buffer:ArrayBuffer,texts:string[],family="Noto Sans KR Local"):SerializableFontMetrics{
  const view=new DataView(buffer),tables=new Map<string,{offset:number;length:number}>(),tableCount=view.getUint16(4);for(let i=0;i<tableCount;i++){const at=12+i*16;tables.set(tag(view,at),{offset:view.getUint32(at+8),length:view.getUint32(at+12)})}
  const required=(name:string)=>{const table=tables.get(name);if(!table)throw new Error(`Font table ${name} is missing`);return table.offset},head=required("head"),hhea=required("hhea"),hmtx=required("hmtx"),maxp=required("maxp"),cmap=required("cmap"),unitsPerEm=view.getUint16(head+18),numberOfHMetrics=view.getUint16(hhea+34),glyphCount=view.getUint16(maxp+4);
  const subtables=view.getUint16(cmap+2),candidates:Array<{offset:number;format:number;priority:number}>=[];for(let i=0;i<subtables;i++){const at=cmap+4+i*8,platform=view.getUint16(at),encoding=view.getUint16(at+2),offset=cmap+view.getUint32(at+4),format=view.getUint16(offset),priority=(format===12?100:format===4?50:0)+(platform===3?10:0)+(encoding===10?5:0);if(format===12||format===4)candidates.push({offset,format,priority})}const selected=candidates.sort((a,b)=>b.priority-a.priority)[0];if(!selected)throw new Error("Font has no supported Unicode cmap (format 4 or 12)");
  const glyphFor=(code:number)=>{if(selected.format===12){const groups=view.getUint32(selected.offset+12);let low=0,high=groups-1;while(low<=high){const mid=(low+high)>>1,at=selected.offset+16+mid*12,start=view.getUint32(at),end=view.getUint32(at+4);if(code<start)high=mid-1;else if(code>end)low=mid+1;else return view.getUint32(at+8)+(code-start)}return 0}const segCount=view.getUint16(selected.offset+6)/2,endAt=selected.offset+14,startAt=endAt+segCount*2+2,deltaAt=startAt+segCount*2,rangeAt=deltaAt+segCount*2;for(let i=0;i<segCount;i++){const end=view.getUint16(endAt+i*2),start=view.getUint16(startAt+i*2);if(code<start||code>end)continue;const delta=view.getInt16(deltaAt+i*2),range=view.getUint16(rangeAt+i*2);if(range===0)return(code+delta)&0xffff;const glyphAddress=rangeAt+i*2+range+(code-start)*2,glyph=view.getUint16(glyphAddress);return glyph===0?0:(glyph+delta)&0xffff}return 0};
  const advanceFor=(glyph:number)=>{if(glyph<0||glyph>=glyphCount)throw new Error(`Invalid glyph ${glyph}`);return view.getUint16(hmtx+Math.min(glyph,numberOfHMetrics-1)*4)},advances:Record<string,number>={};for(const text of texts)for(const character of text){const code=character.codePointAt(0)!;if(advances[String(code)]!==undefined)continue;const glyph=glyphFor(code);if(glyph===0&&code!==0)throw new Error(`Font ${family} has no glyph for U+${code.toString(16).toUpperCase()}`);advances[String(code)]=advanceFor(glyph)}return {family,unitsPerEm,advances};
}

export function measureTextWithFont(metrics:SerializableFontMetrics,text:string,letterSpacing=0){let width=0,count=0;for(const character of text){const code=String(character.codePointAt(0)!),advance=metrics.advances[code];if(advance===undefined)throw new Error(`Font metrics ${metrics.family} do not contain U+${Number(code).toString(16).toUpperCase()}`);width+=advance/metrics.unitsPerEm;count++}return width+Math.max(0,count-1)*letterSpacing}

const isLocalIdeograph=(code:number)=>/\p{Ideo}|\p{sc=Hang}|\p{sc=Hira}|\p{sc=Kana}/u.test(String.fromCodePoint(code))||(code>=0x3000&&code<=0x30ff)||(code>=0xff00&&code<=0xffef);
function pbfAdvances(buffer:Uint8Array){let position=0;const readVarint=()=>{let value=0,shift=0;while(position<buffer.length){const byte=buffer[position++];value+=(byte&127)*2**shift;if(!(byte&128))return value;shift+=7}throw new Error("Truncated glyph PBF varint")},skip=(wire:number,end?:number)=>{if(wire===0)readVarint();else if(wire===2&&end!==undefined)position=end;else if(wire===5)position+=4;else if(wire===1)position+=8;else throw new Error(`Unsupported glyph PBF wire type ${wire}`)},readMessage=(end:number,visitor:(field:number,wire:number,end:number)=>void)=>{while(position<end){const key=readVarint(),wire=key&7,field=key>>3;if(wire===2){const length=readVarint(),next=position+length;visitor(field,wire,next);position=next}else visitor(field,wire,end)}};const advances=new Map<number,number>();readMessage(buffer.length,(rootField,wire,rootEnd)=>{if(rootField!==1||wire!==2){skip(wire,rootEnd);return}const fontstackEnd=rootEnd;readMessage(fontstackEnd,(stackField,stackWire,stackEnd)=>{if(stackField!==3||stackWire!==2){skip(stackWire,stackEnd);return}let id:number|undefined,advance:number|undefined;readMessage(stackEnd,(glyphField,glyphWire,glyphEnd)=>{if(glyphField===1&&glyphWire===0)id=readVarint();else if(glyphField===7&&glyphWire===0)advance=readVarint();else skip(glyphWire,glyphEnd)});if(id!==undefined&&advance!==undefined)advances.set(id,advance)})});return advances}
export function createMapLibreCountryLabelMetrics(otfBuffer:ArrayBuffer,glyphPbfBuffers:Uint8Array[],texts:string[]):SerializableFontMetrics{const noto=extractFontMetrics(otfBuffer,texts.filter(text=>[...text].some(character=>isLocalIdeograph(character.codePointAt(0)!))),MAPLIBRE_COUNTRY_LABEL_FONT.localIdeographFontFamily),serverAdvances=new Map(glyphPbfBuffers.flatMap(buffer=>[...pbfAdvances(buffer)])),advances:Record<string,number>={};for(const text of texts)for(const character of text){const code=character.codePointAt(0)!;if(advances[String(code)]!==undefined)continue;if(isLocalIdeograph(code)){const advance=noto.advances[String(code)];if(advance===undefined)throw new Error(`Local ideograph font has no glyph for U+${code.toString(16).toUpperCase()}`);advances[String(code)]=advance/noto.unitsPerEm*24}else{const advance=serverAdvances.get(code);if(advance===undefined)throw new Error(`MapLibre glyph source ${MAPLIBRE_COUNTRY_LABEL_FONT.textFont} has no glyph for U+${code.toString(16).toUpperCase()}`);advances[String(code)]=advance}}return {family:MAPLIBRE_COUNTRY_LABEL_FONT.calculationFont,unitsPerEm:24,advances}}
