import {create,type FontkitPathCommand} from "fontkit";

export type OutlinePosition=[number,number];
export type GlyphOutlinePolygon={outer:OutlinePosition[];holes:OutlinePosition[][]};
export type ShapedGlyphOutline={glyphIndex:number;codePoint:number;glyphId:number;advance:number;xOffset:number;yOffset:number;polygons:GlyphOutlinePolygon[]};
export type ShapedFontOutline={fontHash:string;unitsPerEm:number;text:string;glyphs:ShapedGlyphOutline[];totalAdvance:number;flattenTolerance:number;letterSpacingEm:number};

const round=(value:number)=>Math.round(value*1e6)/1e6;
const lineDistance=(point:OutlinePosition,start:OutlinePosition,end:OutlinePosition)=>{const dx=end[0]-start[0],dy=end[1]-start[1];return dx===0&&dy===0?Math.hypot(point[0]-start[0],point[1]-start[1]):Math.abs(dy*point[0]-dx*point[1]+end[0]*start[1]-end[1]*start[0])/Math.hypot(dx,dy)};
const splitCubic=(p0:OutlinePosition,p1:OutlinePosition,p2:OutlinePosition,p3:OutlinePosition)=>{const mid=(a:OutlinePosition,b:OutlinePosition):OutlinePosition=>[(a[0]+b[0])/2,(a[1]+b[1])/2],a=mid(p0,p1),b=mid(p1,p2),c=mid(p2,p3),d=mid(a,b),e=mid(b,c),f=mid(d,e);return [[p0,a,d,f],[f,e,c,p3]] as const};
function flattenCubic(p0:OutlinePosition,p1:OutlinePosition,p2:OutlinePosition,p3:OutlinePosition,tolerance:number,output:OutlinePosition[],depth=0){if(Math.max(lineDistance(p1,p0,p3),lineDistance(p2,p0,p3))<=tolerance||depth>=20){output.push(p3);return}const [left,right]=splitCubic(p0,p1,p2,p3);flattenCubic(...left,tolerance,output,depth+1);flattenCubic(...right,tolerance,output,depth+1)}
const area=(ring:OutlinePosition[])=>ring.slice(0,-1).reduce((sum,p,index)=>{const q=ring[index+1];return sum+p[0]*q[1]-q[0]*p[1]},0)/2;
const pointInRing=(point:OutlinePosition,ring:OutlinePosition[])=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside};
function flattenCommands(commands:FontkitPathCommand[],tolerance:number){const rings:OutlinePosition[][]=[];let ring:OutlinePosition[]|null=null,current:OutlinePosition|null=null,start:OutlinePosition|null=null;for(const item of commands){const a=item.args;if(item.command==="moveTo"){ring=[[a[0],a[1]]];rings.push(ring);current=ring[0];start=current}else if(item.command==="lineTo"&&ring){current=[a[0],a[1]];ring.push(current)}else if(item.command==="bezierCurveTo"&&ring&&current){const points:OutlinePosition[]=[];flattenCubic(current,[a[0],a[1]],[a[2],a[3]],[a[4],a[5]],tolerance,points);ring.push(...points);current=[a[4],a[5]]}else if(item.command==="quadraticCurveTo"&&ring&&current){const control:OutlinePosition=[a[0],a[1]],end:OutlinePosition=[a[2],a[3]],c1:OutlinePosition=[current[0]+2/3*(control[0]-current[0]),current[1]+2/3*(control[1]-current[1])],c2:OutlinePosition=[end[0]+2/3*(control[0]-end[0]),end[1]+2/3*(control[1]-end[1])],points:OutlinePosition[]=[];flattenCubic(current,c1,c2,end,tolerance,points);ring.push(...points);current=end}else if(item.command==="closePath"&&ring&&current&&start&&(current[0]!==start[0]||current[1]!==start[1]))ring.push(start)}return rings.filter(ring=>ring.length>=4).map(ring=>ring.map(p=>[round(p[0]),round(p[1])] as OutlinePosition))}
function polygonize(rings:OutlinePosition[][]):GlyphOutlinePolygon[]{const classified=rings.map((ring,index)=>({ring,index,area:area(ring),depth:rings.filter((other,otherIndex)=>otherIndex!==index&&pointInRing(ring[0],other)).length})),outers=classified.filter(item=>item.depth%2===0).sort((a,b)=>Math.abs(b.area)-Math.abs(a.area)||a.index-b.index);return outers.map(outer=>{const holes=classified.filter(item=>item.depth===outer.depth+1&&pointInRing(item.ring[0],outer.ring)).sort((a,b)=>Math.abs(b.area)-Math.abs(a.area)||a.index-b.index).map(item=>item.ring);return {outer:outer.ring,holes}})}
export function shapeFontOutlines(fontBytes:Uint8Array,fontHash:string,text:string,flattenTolerance=1,letterSpacingEm=0):ShapedFontOutline{if(!text)throw new Error("Label text is empty");if(!(flattenTolerance>0))throw new Error("Flatten tolerance must be positive");const font=create(fontBytes),run=font.layout(text),characters=[...text];if(run.glyphs.length!==characters.length)throw new Error(`Shaping changed glyph count for ${text}: ${run.glyphs.length} !== ${characters.length}`);let totalAdvance=0;const glyphs=run.glyphs.map((glyph,glyphIndex)=>{if(glyph.id===0)throw new Error(`Missing glyph U+${characters[glyphIndex].codePointAt(0)!.toString(16).toUpperCase()}`);const position=run.positions[glyphIndex],advance=position.xAdvance;totalAdvance+=advance;return {glyphIndex,codePoint:characters[glyphIndex].codePointAt(0)!,glyphId:glyph.id,advance,xOffset:position.xOffset,yOffset:position.yOffset,polygons:polygonize(flattenCommands(glyph.path.commands,flattenTolerance))}});return {fontHash,unitsPerEm:font.unitsPerEm,text,glyphs,totalAdvance,flattenTolerance,letterSpacingEm}}
