import fs from "node:fs";
import path from "node:path";
import {describe,expect,it} from "vitest";
import countries from "@/data/countries-2020.json";
import metrics from "@/data/country-label-metrics-2020.json";

const root=process.cwd(),read=(name:string)=>JSON.parse(fs.readFileSync(path.join(root,name),"utf8"));
const required=["KOR","PRK","USA","CHN","JPN","SGP","BHR","MDV","MLT","AND","LIE","MCO","SMR","VAT"];
const adminRequired=["USA","CHN","FIN","KAZ","GBR","FRA"];
const playableRequired=["PSX","SDS","SOL"];
type PolygonGeometry={type:"Polygon"|"MultiPolygon";coordinates:number[][][]|number[][][][]};
const pointInRing=(point:number[],ring:number[][])=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j],cross=(point[0]-a[0])*(b[1]-a[1])-(point[1]-a[1])*(b[0]-a[0]),onSegment=Math.abs(cross)<=1e-9&&point[0]>=Math.min(a[0],b[0])-1e-9&&point[0]<=Math.max(a[0],b[0])+1e-9&&point[1]>=Math.min(a[1],b[1])-1e-9&&point[1]<=Math.max(a[1],b[1])+1e-9;if(onSegment)return true;if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside};
const pointInGeometry=(point:number[],geometry:PolygonGeometry)=>{const polygons:number[][][][]=geometry.type==="Polygon"?[geometry.coordinates as number[][][]]:geometry.coordinates as number[][][][];return polygons.some(polygon=>pointInRing(point,polygon[0])&&!polygon.slice(1).some(ring=>pointInRing(point,ring)))};

describe("generated map data",()=>{
  const ids=new Set(countries.map(c=>c.id)),admin=read("public/data/maps/admin1-boundaries-10m.geojson"),report=read("public/data/maps/admin1-validation-2020.json"),countriesHigh=read("public/data/maps/countries-10m.geojson"),bordersHigh=read("public/data/maps/country-borders-10m.geojson"),baselines=read("public/data/maps/country-label-baselines-2020.geojson"),pointLabels=read("public/data/maps/country-labels-2020.geojson"),capitals=read("public/data/maps/capitals-2020.geojson");
  it("contains required localized countries without duplicate ids",()=>{expect(ids.size).toBe(countries.length);for(const id of required){const country=countries.find(c=>c.id===id);expect(country?.nameKo).toBeTruthy()}});
  it("separates playable sovereign countries from map units",()=>{expect(countries.some(c=>!c.playable)).toBe(true);expect(countries.find(c=>c.id==="ATA")?.playable).toBe(false);expect(countries.filter(c=>c.playable).every(c=>ids.has(c.id))).toBe(true)});
  it("keeps the Cyprus buffer zone and correctly names the Spratly Islands",()=>{expect(ids.has("CNM")).toBe(true);const spratly=countries.find(c=>c.id==="PGA");expect(spratly?.nameEn).toBe("Spratly Islands");expect(spratly?.nameKo).toBe("스프래틀리 군도");expect(spratly?.unitType).toBe("disputed-territory")});
  it("keeps Palestine, South Sudan, and Somaliland playable",()=>{for(const id of playableRequired){const country=countries.find(c=>c.id===id);expect(country?.playable).toBe(true);expect(country?.unitType).toBe("sovereign-country")}expect(ids.has("PSE")).toBe(false);expect(ids.has("SSD")).toBe(false)});
  it("removes merged and excluded map units as standalone countries",()=>{for(const id of ["KAS","KAB","SPI","BRT","BRI","ESB","WSB","USG","BJN","SER","SCR"]){expect(ids.has(id)).toBe(false);expect(countriesHigh.features.some((f:{properties:{countryId:string}})=>f.properties.countryId===id)).toBe(false);expect(baselines.features.some((f:{properties:{countryId:string}})=>f.properties.countryId===id)).toBe(false);expect(admin.features.some((f:{properties:{countryId:string}})=>f.properties.countryId===id)).toBe(false)}expect(report.removedMapUnits.map((x:{adm0_a3:string})=>x.adm0_a3).sort()).toEqual(["ESB","KAB","KAS","USG","WSB"])});
  it("omits removed-unit outlines and the Chukotka dateline seam from country borders",()=>{expect(bordersHigh.features).toHaveLength(countries.length);for(const feature of bordersHigh.features){for(const line of feature.geometry.coordinates){for(let i=1;i<line.length;i++){const a=line[i-1],b=line[i];expect(Math.abs(Math.abs(a[0])-180)<1e-5&&Math.abs(Math.abs(b[0])-180)<1e-5).toBe(false)}}}},30_000);
  it("reports actual final Admin 1 boundary features",()=>{expect(report.unresolved).toEqual([]);expect(report.excluded).toEqual([]);expect(report.summary.every((r:{rawAdmin1Count:number;validGeometryCount:number;generatedBoundaryFeatureCount:number;excludedInvalidGeometryCount:number})=>r.rawAdmin1Count===r.validGeometryCount+r.excludedInvalidGeometryCount&&r.generatedBoundaryFeatureCount<=r.validGeometryCount)).toBe(true);for(const row of report.summary){const actual=admin.features.filter((f:{properties:{countryId:string}})=>f.properties.countryId===row.countryId).length;expect(row.generatedBoundaryFeatureCount).toBe(actual)}expect(admin.features.every((f:{properties:{countryId:string;admin1Id:string}})=>ids.has(f.properties.countryId)&&!!f.properties.admin1Id)).toBe(true);for(const id of [...adminRequired,"KOR","JPN","IND"])expect(report.samples[id].generatedBoundaryFeatureCount).toBeGreaterThan(0)});
  it("partitions every country into one curved line or Point fallback",()=>{const allIds=new Set(countries.map(c=>c.id)),lineIds=new Set<string>(baselines.features.map((f:{properties:{countryId:string}})=>f.properties.countryId)),fallbackIds=new Set<string>(pointLabels.features.filter((f:{properties:{placementMode:string}})=>f.properties.placementMode==="small-country-point").map((f:{properties:{countryId:string}})=>f.properties.countryId));expect(pointLabels.features).toHaveLength(countries.length);expect(new Set(pointLabels.features.map((f:{properties:{countryId:string}})=>f.properties.countryId))).toEqual(allIds);expect(baselines.features.every((f:{geometry:{type:string;coordinates:number[][]};properties:{placementMode:string;insideRatio:number}})=>f.geometry.type==="LineString"&&f.geometry.coordinates.length>=13&&f.geometry.coordinates.length<=25&&f.properties.placementMode==="curved-line"&&f.properties.insideRatio>0)).toBe(true);expect([...lineIds].filter(id=>fallbackIds.has(id))).toEqual([]);expect(new Set([...lineIds,...fallbackIds])).toEqual(allIds)});
  it("keeps playable point-fallback anchors on territory and exposes curved-label shape metrics",()=>{const geometryById=new Map<string,PolygonGeometry>(countriesHigh.features.map((f:{properties:{countryId:string};geometry:PolygonGeometry})=>[f.properties.countryId,f.geometry]));for(const feature of pointLabels.features.filter((f:{properties:{countryId:string;placementMode:string}})=>f.properties.placementMode==="small-country-point"&&countries.find(c=>c.id===f.properties.countryId)?.playable)){expect(pointInGeometry(feature.geometry.coordinates,geometryById.get(feature.properties.countryId)!),feature.properties.countryId).toBe(true)}for(const id of ["RUS","CAN","USA","CHN","BRA","AUS","IND"]){const metric=metrics.find(m=>m.countryId===id)!;expect(metric.baselineLengthDegrees).toBeGreaterThan(0);expect(metric.targetTextWidthWorld).toBeGreaterThan(0);expect(metric.insideRatio).toBeGreaterThan(.65);expect(metric.coverageRatio).toBeGreaterThan(.5)}});
  it("keeps small-country minZoom and placement exclusive",()=>{for(const id of ["VAT","MCO","SMR","LIE","SGP"]){const metric=metrics.find(m=>m.countryId===id)!,feature=pointLabels.features.find((f:{properties:{countryId:string}})=>f.properties.countryId===id);expect(metric.minZoom).toBeGreaterThan(5);expect(feature.properties.placementMode).toBe("small-country-point")}expect(pointLabels.features.filter((f:{properties:{countryId:string}})=>f.properties.countryId==="VAT")).toHaveLength(1)});
  it("does not place every country label at its capital",()=>{const capitalById=new Map(capitals.features.map((f:{properties:{countryId:string};geometry:{coordinates:number[]}})=>[f.properties.countryId,f.geometry.coordinates]));const distinct=pointLabels.features.filter((f:{properties:{countryId:string};geometry:{coordinates:number[]}})=>JSON.stringify(f.geometry.coordinates)!==JSON.stringify(capitalById.get(f.properties.countryId)));expect(distinct.length).toBeGreaterThan(220)});
  it("uses the geometry anomaly fallback only for the detected extreme outlier",()=>{const fallbackIds=metrics.filter(metric=>metric.searchDiagnostics.centerFallbackApplied).map(metric=>metric.countryId);expect(fallbackIds).toEqual(["NOR"]);const norway=metrics.find(metric=>metric.countryId==="NOR")!;expect(norway.searchDiagnostics.centerSpanGain).toBeGreaterThan(8)});
});
