import {test,expect} from "./legacy-fixture";
import path from "node:path";

const representatives=["USA","RUS","CHN"] as const,zoomCountries=["AUS","RUS"] as const,boundaries=[1.2499,1.25,1.2501,1.4999,1.5,1.5001] as const;
type Measurement={countryId:string;zoom:number;worldCopy:number;glyphCount:number;instanceCount:number;boundsCount:number;labelWidth:number;territoryWidth:number;widthRatio:number};

test("8-7 representative zoom continuity",async({page})=>{
  await page.setViewportSize({width:1440,height:900});await page.goto("/");await expect(page.getByRole("status").first()).toBeHidden({timeout:90_000});
  const stable=async()=>{await expect.poll(()=>page.evaluate(()=>window.__PAX_MAP_DEBUG__?.isRenderSettled()??false),{timeout:60_000}).toBe(true);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));expect(await page.evaluate(()=>window.__PAX_MAP_DEBUG__!.isRenderSettled())).toBe(true)};
  await stable();expect(await page.evaluate(()=>window.__PAX_MAP_DEBUG__!.getCenter())).toEqual([45,25]);expect(await page.evaluate(()=>window.__PAX_MAP_DEBUG__!.getZoom())).toBe(1);const initial=await page.evaluate(()=>window.__PAX_MAP_DEBUG__!.getRenderedGlyphLabelIds?.()??[]);for(const id of representatives)expect(initial).toContain(id);
  const measure=async(countryId:string,zoom:number):Promise<Measurement>=>{const placement=await page.evaluate(id=>window.__PAX_MAP_DEBUG__!.getCountryLabelPlacement(id),countryId) as {anchor:[number,number];footprint:{coordinates:[number,number][][]}};await page.evaluate(({anchor,zoom})=>window.__PAX_MAP_DEBUG__!.jumpTo(anchor,zoom),{anchor:placement.anchor,zoom});await stable();return page.evaluate(({countryId,zoom,footprint})=>{const debug=window.__PAX_MAP_DEBUG__!,bounds=debug.getCountryLabelRendererBounds?.(countryId)??[],vertices=footprint.coordinates.flat().map(point=>debug.project(point)),left=Math.min(...vertices.map(point=>point[0])),right=Math.max(...vertices.map(point=>point[0])),territoryWidth=right-left,labelWidth=bounds[0]?.width??0;return {countryId,zoom,worldCopy:bounds[0]?.worldCopy??Number.NaN,glyphCount:debug.getGlyphLabelFeatureCount?.(countryId)??0,instanceCount:debug.getGlyphLabelInstanceCount?.(countryId)??0,boundsCount:bounds.length,labelWidth,territoryWidth,widthRatio:labelWidth/territoryWidth}}, {countryId,zoom,footprint:placement.footprint})};
  const zoomEvidence:Measurement[]=[];for(const countryId of zoomCountries){for(const zoom of [1,2,3]){const value=await measure(countryId,zoom);expect(value.boundsCount).toBe(1);expect(value.instanceCount).toBe(1);expect(value.glyphCount).toBe(countryId==="AUS"?7:3);expect(value.labelWidth).toBeGreaterThan(0);expect(value.territoryWidth).toBeGreaterThan(0);expect(value.widthRatio).toBeLessThanOrEqual(1.15);zoomEvidence.push(value);await page.screenshot({path:path.join(process.cwd(),`screenshots/fix08-7-${countryId.toLowerCase()}-z${zoom}.png`)})}const ratios=zoomEvidence.filter(value=>value.countryId===countryId).map(value=>value.widthRatio);expect(Math.max(...ratios)-Math.min(...ratios)).toBeLessThan(.002)}
  const boundaryRuns:Measurement[][]=[];for(let run=0;run<2;run++){const evidence:Measurement[]=[];for(const countryId of zoomCountries)for(const zoom of boundaries){const value=await measure(countryId,zoom);expect(value.boundsCount).toBe(1);expect(value.instanceCount).toBe(1);expect(value.labelWidth).toBeGreaterThan(0);evidence.push(value)}boundaryRuns.push(evidence)}
  expect(boundaryRuns[1].map(value=>({countryId:value.countryId,zoom:value.zoom,glyphCount:value.glyphCount,instanceCount:value.instanceCount,boundsCount:value.boundsCount,widthRatio:Number(value.widthRatio.toFixed(6))}))).toEqual(boundaryRuns[0].map(value=>({countryId:value.countryId,zoom:value.zoom,glyphCount:value.glyphCount,instanceCount:value.instanceCount,boundsCount:value.boundsCount,widthRatio:Number(value.widthRatio.toFixed(6))})));
  console.log("FIX08_7_SUMMARY",JSON.stringify({viewport:[1440,900],initialCenter:[45,25],initialZoom:1,initialRendered:representatives,zoomEvidence,boundaryRuns}));
});
